### ISSUE TITLE
Can't create twoinstance in the same form

### ISSUE THREAD

**Issue by nourdar** [heloufir/filament-leaflet-geosearch#1]
Hello,
I tried to create a form that allows users to choose two addresses, one for the sender and the second for the receiver.
that's my code : 

```php
LeafletInput::make('adress_france')
    ->label('Adress France : ')
    ->setMapHeight(300) 
    ->setZoomControl(false) 
    ->setScrollWheelZoom(false) 
    ->setZoomLevel(3), 

  LeafletInput::make('adress_algerie')
    ->label('Adress Algeria : ')
    ->setMapHeight(300) 
    ->setZoomControl(false) 
    ->setScrollWheelZoom(false) 
    ->setZoomLevel(3), 
```

In the result, only Algeria address showed up.

**Comment by heloufir** [comment]
Hello @nourdar,

I just released a fix in the 1.1.1 version, can you please update the plugin and check if it's working now.

PS. Don't forget to use the new way of registering styles / scripts [https://github.com/heloufir/filament-leaflet-geosearch#installation](https://github.com/heloufir/filament-leaflet-geosearch#installation)
